---
title: "WCR7"
author: "Abigail Gaudette"
date: "2024-11-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rgbif)
library(tidyverse)
library(MuMIn)
library(data.table)
library(ggmap)
library(usmap)
library(lme4)
library(car)
library(rnoaa)
library(parallel)
library(magick)
library(cowplot)
```

```{r}
species <- c("Piranga olivacea", "Pheucticus ludovicianus", "Dolichonyx oryzivorus", "Icterus spurius", "Icterus galbula")
years <- 2000:2019
months <- c(4, 5) # April and May

fetch_data_for_species_year <- function(species, year) {
  occ_data(
    scientificName = species,
    year = year,
    month = months,
    limit = 5000,
    country = "US",
    basisOfRecord = "HUMAN_OBSERVATION",
    stateProvince = "Massachusetts"
  )[[2]]
}
fetch_data_for_species <- function(species) {
  results <- mclapply(years, function(year) {
    fetch_data_for_species_year(species, year)
  }, mc.cores = detectCores() - 1)
  
  rbindlist(results, fill = TRUE)
}
all_species_data <- rbindlist(lapply(species, fetch_data_for_species), fill = TRUE)
head(all_species_data)
saveRDS(all_species_data,"massbird.data.RDS")
dat <- readRDS("massbird.data.RDS")
dat%>%
  group_by(year,species)%>%
  summarise(count=sum(individualCount,na.rm = T))%>%
  ggplot(aes(x=year,y=count,col=species))+geom_point()
```

```{r}
mc<- dat%>%
  group_by(species, year)%>%
  mutate(date=as.Date(paste0(year,"-",month,"-",day)),
         j.day=julian(date,origin=as.Date(paste0(unique(year),"-01-01")))
  )%>%
  group_by(species,year,j.day,date)%>%
  summarise(day.tot=sum(individualCount,na.rm=T))%>%
  group_by(species,year)%>%
  mutate(prop=cumsum(day.tot/sum(day.tot,na.rm = T)))%>%
  filter(year>2000)
mc.pred <- mc%>%
  group_by(species, year)%>%
  summarize(
    pred=predict(nls(prop~SSlogis(j.day,Asym, xmid, scal)),newdata=data.frame(j.day=min(j.day):max(j.day))),    j.day=min(j.day):max(j.day),
  )%>%
  left_join(mc%>%dplyr::select(species, year, j.day,date)) 
mc.arrive.date <-mc.pred%>%
  group_by(species, year)%>%
  filter(j.day==j.day[which.min(abs(pred-0.25))])
```

```{r}
options(noaakey = "EwrkZUCBvfZZkbgInioAZoyPyXtAXTWp")
sts <- c(
  "GHCND:USW00013894", #Mobible, AL 2k away about 10 days away @200 km/day
  "GHCND:USW00013881", #Charlotte, NC 1000 km away about 6 days away @200 km/day
  "GHCND:USW00014739" #Boston
)
sta.d <- bind_rows( #bind the rows
  lapply(sts,function(x) ncdc_stations(stationid = x)$data ) 
)%>%
  mutate(usmap_transform(.,input_names = c("longitude","latitude"),output_names = c("longitude.1", "latitude.1")))%>% 
  mutate(name=str_sub(name, -5,-4))%>%
  mutate(migr.day=c(10,5,0))%>% 
  separate(id,into = c("station.type","id"))%>%
    print()
sta.d <- bind_rows( 
  lapply(sts,function(x) ncdc_stations(stationid = x)$data ) 
  )%>%
  mutate(usmap_transform(.,input_names = c("longitude","latitude"),output_names = c("longitude.1", "latitude.1")))%>% 
  mutate(name=str_sub(name, -5,-4))%>%
  mutate(migr.day=c(10,5,0))%>% 
  separate(id,into = c("station.type","id"))%>%
        print()
weather.d <- meteo_pull_monitors(sta.d$id,date_min = "2000-01-01")
head(weather.d)
weather.d <- weather.d%>%
  mutate(year=as.integer(str_sub(date,1,4)), 
         date=as.Date(date))%>%
  group_by(year)%>% 
  mutate(j.day=julian(date,origin=as.Date(paste0(unique(year),"-01-01"))), 
         date2=date,
         wdir.rad=(180-abs(wdf2-180))*pi/180, 
         wvec=cos(wdir.rad)*-1*awnd 
  )%>% 
  dplyr::select(id,year,date2,j.day,tmin,tmax,wvec)%>% 
  left_join(sta.d%>%select(id,name,migr.day))%>%
  mutate(j.day=j.day+migr.day)
mc.arr.weath <- mc.arrive.date%>%
  left_join(weather.d)%>%
  left_join(mc%>%dplyr::select(year,date,j.day))
weather.wk <- weather.d %>% 
  group_by(year, name) %>% 
  mutate(
    wk.tmin = frollmean(tmin, n = 14, align = "right"),  
    wk.tmax = frollmean(tmax, n = 14, align = "right"),
    wk.wvec = frollmean(wvec, n = 14, align = "right")
  ) %>%
  select(j.day, date2, name, wk.tmin, wk.tmax, wk.wvec)
mc.arr.weath2 <- mc.arrive.date%>%
  left_join(weather.wk)
```

```{r}
mc.lmer <- lmer(j.day~tmin*tmax*wvec+(1|name),mc.arr.weath,na.action = "na.fail")
mc.lmer2 <- lmer(j.day ~ wk.tmin * wk.tmax * wk.wvec + (1|name), mc.arr.weath2, na.action = "na.fail")

mc.arr.aic <- dredge(mc.lmer2, fixed = c("wk.tmin", "wk.tmax", "wk.wvec"))
mc.arr.aic

Anova(mc.lmer)
Anova(mc.lmer2)
best.lmer <- lmer(j.day ~ wk.tmin + wk.tmax + wk.wvec + (1|name), mc.arr.weath2, na.action = "na.fail")
Anova(best.lmer)
```
